#!/usr/bin/env python3

import sys
import wikipedia
import wikitextparser as wtp
from mako.template import Template

wikipedia.set_lang("de")

mandoc = '''
.Dd $Mdocdate: 30.11.2019 $
.Dt Wikipedia
.Os
.Sh NAME
.Nm ${title}
.Nd ${url}
% for section in sections:
    % if loop.index == 0:
.Sh ZUSAMMENFASSUNG
    % else:
.Sh ${section.title}
    % endif
${section.contents}
% endfor
.Ed
.Sh Links
% for link in links:
.It
.Xr ${link}
% endfor
'''


def get_article(name):

    if name is None:
        sys.exit(1)

    article = wikipedia.page(name)

    return article


def render_article(article, template=mandoc):

    mdoc = Template(template)

    sections = wtp.parse(article.content).sections

    rendered = mdoc.render(title=article.title,
            links=article.links,
            sections=sections,
            url=article.url,
            )

    print(rendered)


render_article(article=get_article(sys.argv[1]), template=mandoc)
