
.Dd 2019-12-02 $
.Dt Wikipedia de
.Os
.Sh NAME
.Nm LOL
.Nd https://de.wikipedia.org/wiki/LOL
.Sh Zusammenfassung

LOL, Akronym für Laughing Out Loud oder auch laugh out loud, (dt. „laut lachen“, wörtlich „laut auflachen“) ist ein Wort aus dem Netzjargon und wird als Reaktion auf etwas Lustiges oder Außergewöhnliches, aber auch für „auslachen“ gebraucht.



.Sh  Ursprung und Verbreitung 

LOL wurde als Abkürzung für laughing out loud erstmals in den 1980er Jahren verwendet. Im Usenet verfasste der Benutzer Wayne Pearson eine Nachricht, die das Wort LOL beinhaltete. Die Abkürzung wird häufig in E-Mails, SMS-Nachrichten, Computerspielen und Chats verwendet. Daneben hat es sich auch als Bestandteil der Jugendsprache etabliert. 2011 wurde der Begriff in das Oxford English Dictionary aufgenommen.



.Sh  Variationen und Ableitungen 


„LOL“ bietet eine Vielzahl von Variationen.

lolz, lulz, löl, lel (kein direkter Unterschied zu LOL)
ROFL oder ROTFL (rolling on [the] floor laughing), Ableitung: ROFLCOPTER (eine animierte ASCII-Art Darstellung; erstes Erscheinen vermutlich 2004)
LMAO (Laughing my ass off) und LMFAO (Laughing my fucking ass off)
lqtm (Laughing quietly to myself)
kek hat seinen Ursprung in World of Warcraft. Dort gibt es zwei Fraktionen, die Allianz und die Horde, deren Spieler nicht miteinander kommunizieren können. Öffentliche Aussprüche werden für Spieler der gegnerischen Fraktion in Kauderwelsch umgewandelt. lol wird dabei als kek angezeigt, und umgekehrt. Um einen gegnerischen Spieler mit lol auszulachen, gibt man im Spiel /say kek ein. Mittlerweile wird kek als Alternative zu lol auch außerhalb solcher Situationen verwendet.



.Sh  Andere Sprachen 

In einigen Ländern existieren bedeutungsgleiche Koexistenzen zu dem Wort LOL:

Im Arabischen existieren zwei Schreibweisen, zum einen die transliterierte Variante لــول oder هـــا, was wie ha ausgesprochen wird.
Französisch: mdr, aus den Initialen von mort de rire (deutsch „totgelacht“)
Hebräisch: ההה, dessen Aussprache in etwa „hahaha“ entspricht, also als Lachen gedeutet werden kann.
Im Japanischen wurde ursprünglich das Kanji für Lachen/Lächeln in Klammern gesetzt – (笑). Da dieses als wara(u) ausgesprochen wird, wird es heute üblicherweise einfach nur mit w abgekürzt.
Im Koreanischen existieren ebenfalls zwei Schreibweisen, einerseits ᄒᄒᄒ, was wie hehehe ausgesprochen wird, andererseits ᄏᄏᄏ, was wie kekeke ausgesprochen wird.
Schwedisch: Hier ist die Abkürzung asg für Asgarv (deutsch „starkes Lachen“) gebräuchlich.
Die Thai-Fassung von LOL ist 555, da die Ziffer 5 als ha ausgesprochen wird.
In einigen Sprachen mit nicht-lateinischer Schrift werden die Buchstaben oft transliteriert, z. B. russisch лол.



.Sh  Siehe auch 

Liste von Abkürzungen (Netzjargon)



.Sh  Weblinks 


Lol und übelst sind nicht mehr geil, Digga! auf Welt Online



.Sh  Einzelnachweise 



.Ed
.Sh Links
.It
.Xr ASCII-Art
.Xr Akronym
.Xr Arabische Sprache
.Xr Chat
.Xr Computerspiel
.Xr Deutsche Sprache
.Xr E-Mail
.Xr Französische Sprache
.Xr Hebräische Sprache
.Xr Initialen
.Xr Japanische Sprache
.Xr Jugendsprache
.Xr Kanji
.Xr Koreanische Sprache
.Xr Liste von Abkürzungen (Netzjargon)
.Xr Lol
.Xr Netzjargon
.Xr Oxford English Dictionary
.Xr Russische Sprache
.Xr SMS
.Xr Schwedische Sprache
.Xr Thai-Sprache
.Xr Usenet
.Xr Welt Online
.Xr World of Warcraft

